name: Create Top Languages

on:
  push:
  schedule:
    - cron: "0 */24 * * *"

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Run custom action
        uses: gouef/githubtoplanguages@main
        with:
          user: "coyoteclan"
          limit: 10
          ignoredOrgsFlag: ""
          ignoredReposFlag: ""
        env:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
